#ifndef _CONFIG_H
#define _CONFIG_H

#ifdef __cplusplus
extern "C" {
#endif

#define STATS_NAME "Stats"
#define STATS_PRIO (tskIDLE_PRIORITY + 4)
#define STATS_STACK_SIZE configMINIMAL_STACK_SIZE

#define LED_NAME "LED"
#define LED_PRIO (configMAX_PRIORITIES - 1)
#define LED_STACK_SIZE configMINIMAL_STACK_SIZE

#define SENSOR_NAME "Sensor"
#define SENSOR_PRIO (tskIDLE_PRIORITY + 2)
#define SENSOR_STACK_SIZE configMINIMAL_STACK_SIZE

#define ACTUATOR_NAME "Actuator"
#define ACTUATOR_PRIO (tskIDLE_PRIORITY + 3)
#define ACTUATOR_STACK_SIZE configMINIMAL_STACK_SIZE

#define COMMS_NAME "Comms"
#define COMMS_PRIO (tskIDLE_PRIORITY + 2)
#define COMMS_STACK_SIZE configMINIMAL_STACK_SIZE

#define IDLE_NAME "IDLE"
#define IDLE_PRIO tskIDLE_PRIORITY
#define IDLE_STACK_SIZE configMINIMAL_STACK_SIZE

#define TIMER_NAME "Tmr Svc"
#define TIMER_PRIO configTIMER_TASK_PRIORITY
#define TIMER_STACK_SIZE configTIMER_TASK_STACK_DEPTH

#define TZCTRL_NAME "TzCtrl"
#define TZCTRL_PRIO TRC_CFG_CTRL_TASK_PRIORITY
#define TZCTRL_STACK_SIZE TRC_CFG_CTRL_TASK_STACK_SIZE

#define IP_NAME "IP-task"
#define IP_PRIO ipconfigIP_TASK_PRIORITY
#define IP_STACK_SIZE ipconfigIP_TASK_STACK_SIZE_WORDS

#define EMAC_NAME "EMAC"
#define EMAC_PRIO nwETHERNET_RX_HANDLER_TASK_PRIORITY
#define EMAC_STACK_SIZE nwRX_TASK_STACK_SIZE

#ifdef __cplusplus
}
#endif

#endif /* _CONFIG_H */
